// This code was generated by a tool.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
public enum LayerNames
{
    Default = 0,
    TransparentFX = 1,
    Ignore_Raycast = 2,
    StageEntities = 3,
    Water = 4,
    UI = 5,
    Walls = 6,
    Ground = 7,
    MapLayout = 8,
    Hazards = 9,
    EntityBarrier = 10,
    MapLayoutWalls = 11,
}
