public enum SceneNames
{
    MainMenu,
    DefaultBattleScene_DoNotModify,
    CircleStage,
    TutorialStage,
    StageSelectionScene_Old,
    DefaultCombatStage,
    IslandsCombatStage,
    MazeCombatStage,
    CircleCombatStage,
    CoinCombatStage,
    HourglassCombatStage,
    RestStage,
    EndingStage,
    TutorialStage_New,
    PracticeStage,
    StageSelectionScene,
}
